- name: Create pods using deployment
  hosts: kubernetes
  # become: true
  # user: ubuntu

  tasks:
  - name: delete the previous deployment
    win_shell: kubectl.exe delete deployment cicd-deployment
    ignore_errors: yes

  - name: create a deployment
    win_command: kubectl apply -f cicd-devops-deployment.yml